
DECLARE
CURSOR EMP_REGIONS IS
SELECT LAST_NAME,DEPARTMENT_NAME,STREET_ADDRESS,COUNTRY_NAME,REGION_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(D.DEPARTMENT_ID=E.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(L.LOCATION_ID=D.LOCATION_ID)
JOIN COUNTRIES C
ON(C.COUNTRY_ID=L.COUNTRY_ID)
JOIN REGIONS R
ON(R.REGION_ID=C.REGION_ID);
BEGIN
   
    FOR REG_EMPREGIONS IN EMP_REGIONS LOOP
   
    DBMS_OUTPUT.PUT_LINE(REG_EMPREGIONS.LAST_NAME|| ' ' ||REG_EMPREGIONS.STREET_ADDRESS);
    END LOOP;
   
END;
/