SET SERVEROUTPUT ON
DECLARE
  
 
    
    CURSOR CUR_EMP IS
    SELECT LAST_NAME,SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID=20;
    
     REG_EMP CUR_EMP%ROWTYPE;
    
BEGIN
    OPEN CUR_EMP;
    FETCH CUR_EMP INTO REG_EMP;
   WHILE CUR_EMP%FOUND LOOP
   
      DBMS_OUTPUT.PUT_LINE(REG_EMP.LAST_NAME|| ' ' ||REG_EMP.SALARY);
      FETCH CUR_EMP INTO REG_EMP;
    END LOOP;
        CLOSE CUR_EMP;
 

END;
/