SELECT LAST_NAME FROM EMPLOYEES;
SELECT LAST_NAME FROM EMPLOYEES
WHERE EMPLOYEE_ID=100;

SET SERVEROUTPUT ON

DECLARE
    V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
SELECT LAST_NAME INTO V_LAST_NAME FROM EMPLOYEES
WHERE EMPLOYEE_ID=100;
DBMS_OUTPUT.PUT_LINE(V_LAST_NAME);
END;
/