SET VERIFY OFF
ACCEPT P_EI PROMPT 'INFORME O NUMERO DO FUNCIONARIO?' 
DECLARE
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE;
    V_SAL EMPLOYEES.SALARY%TYPE;
BEGIN
SELECT LAST_NAME,FIRST_NAME,SALARY INTO V_LAST_NAME ,V_FIRST_NAME,V_SAL FROM EMPLOYEES
WHERE EMPLOYEE_ID=100;
DBMS_OUTPUT.PUT_LINE(V_LAST_NAME ||CHR(10)|| V_FIRST_NAME||CHR(10)||V_SAL);
END;
/

DECLARE 
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE:=&P_EI;
    V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE;
    V_DEP_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
    

BEGIN
    SELECT LAST_NAME,DEPARTMENT_NAME
    INTO V_LAST_NAME,V_DEP_NAME
    FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON(D.DEPARTMENT_ID=E.DEPARTMENT_ID)
    WHERE EMPLOYEE_ID= V_EMPLOYEE_ID;
    
    DBMS_OUTPUT.put_line(V_LAST_NAME||' '||V_DEP_NAME);
END;
/