-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-08-29 09:39:41 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE dim_forma_pgto CASCADE CONSTRAINTS;

DROP TABLE dim_fornencedor CASCADE CONSTRAINTS;

DROP TABLE dim_hospital CASCADE CONSTRAINTS;

DROP TABLE dim_produto CASCADE CONSTRAINTS;

DROP TABLE dim_tempo CASCADE CONSTRAINTS;

DROP TABLE fto_dpto_compras CASCADE CONSTRAINTS;

