-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-08-29 09:39:41 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE dim_forma_pgto (
    sk_pagamento   NUMBER NOT NULL,
    ds_pagamento   VARCHAR2(50),
    qt_parcelas    NUMBER
);

ALTER TABLE dim_forma_pgto ADD CONSTRAINT dim_forma_pgto_pk PRIMARY KEY ( sk_pagamento );

CREATE TABLE dim_fornencedor (
    nm_cidade       VARCHAR2(50),
    nm_fornecedor   VARCHAR2(50),
    sk_cnpj         NUMBER NOT NULL,
    nr_estrelas     NUMBER,
    dt_fundacao     DATE,
    nm_estado       VARCHAR2(50),
    nm_bairro       VARCHAR2(50)
);

ALTER TABLE dim_fornencedor ADD CONSTRAINT dim_fornencedor_pk PRIMARY KEY ( sk_cnpj );

CREATE TABLE dim_hospital (
    sk_hospital   NUMBER NOT NULL,
    nm_hospital   VARCHAR2(50),
    nm_estado     VARCHAR2(50),
    nm_cidade     VARCHAR2(50),
    nm_bairro     VARCHAR2(50)
);

ALTER TABLE dim_hospital ADD CONSTRAINT dim_hospital_pk PRIMARY KEY ( sk_hospital );

CREATE TABLE dim_produto (
    cd_barras      NUMBER NOT NULL,
    tp_embalagem   VARCHAR2(50),
    sk_produto     NUMBER NOT NULL,
    nm_produto     VARCHAR2(50)
);

ALTER TABLE dim_produto ADD CONSTRAINT dim_produto_pk PRIMARY KEY ( sk_produto );

CREATE TABLE dim_tempo (
    sk_tempo           NUMBER NOT NULL,
    ds_data_completa   DATE,
    ds_ano             NUMBER(4),
    ds_mes             NUMBER(2),
    ds_dia             NUMBER(2),
    ds_hora            NUMBER(2)
);

ALTER TABLE dim_tempo ADD CONSTRAINT dim_tempo_pk PRIMARY KEY ( sk_tempo );

CREATE TABLE fto_dpto_compras (
    vl_preco                  NUMBER,
    vl_desconto               NUMBER,
    vl_porc_desconto          NUMBER,
    vl_total                  NUMBER,
    qt_adiquirida             NUMBER,
    qt_dias_enterga           NUMBER,
    vl_porc_imposto           NUMBER,
    vl_imposto                NUMBER,
    dim_fornencedor_sk_cnpj   NUMBER NOT NULL,
    sk_tempo                  NUMBER NOT NULL,
    sk_hospital               NUMBER NOT NULL,
    sk_produto                NUMBER NOT NULL,
    sk_pagamento              NUMBER NOT NULL
);

ALTER TABLE fto_dpto_compras
    ADD CONSTRAINT fto_dpto_compras_pk PRIMARY KEY ( dim_fornencedor_sk_cnpj,
                                                     sk_tempo,
                                                     sk_hospital,
                                                     sk_produto,
                                                     sk_pagamento );

ALTER TABLE fto_dpto_compras
    ADD CONSTRAINT fk_fto_dim_forma_pgto FOREIGN KEY ( sk_pagamento )
        REFERENCES dim_forma_pgto ( sk_pagamento );

ALTER TABLE fto_dpto_compras
    ADD CONSTRAINT fk_fto_dim_fornencedor FOREIGN KEY ( dim_fornencedor_sk_cnpj )
        REFERENCES dim_fornencedor ( sk_cnpj );

ALTER TABLE fto_dpto_compras
    ADD CONSTRAINT fk_fto_dim_hospital FOREIGN KEY ( sk_hospital )
        REFERENCES dim_hospital ( sk_hospital );

ALTER TABLE fto_dpto_compras
    ADD CONSTRAINT fk_fto_dim_produto FOREIGN KEY ( sk_produto )
        REFERENCES dim_produto ( sk_produto );

ALTER TABLE fto_dpto_compras
    ADD CONSTRAINT fk_fto_dim_tempo FOREIGN KEY ( sk_tempo )
        REFERENCES dim_tempo ( sk_tempo );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
