-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-09-12 08:51:59 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE dim_prod_serv (
    sk_prod_serv      NUMBER NOT NULL,
    cd_prod_serv      NUMBER,
    nm_prod_serv      VARCHAR2(50),
    tp_prod_serv      VARCHAR2(10),
    nm_origem_dados   VARCHAR2(40)
);

ALTER TABLE dim_prod_serv ADD CONSTRAINT dim_prod_serv_pk PRIMARY KEY ( sk_prod_serv );

CREATE TABLE dim_tempo (
    sk_tempo        NUMBER NOT NULL,
    dt_evento       DATE,
    nr_dia          NUMBER(2),
    nr_mes          NUMBER(2),
    nr_ano          NUMBER(4),
    nm_dia_semana   VARCHAR2(20),
    nm_trimestre    VARCHAR2(20)
);

ALTER TABLE dim_tempo ADD CONSTRAINT dim_tempo_pk PRIMARY KEY ( sk_tempo );

CREATE TABLE dim_unid_hospitalar (
    sk_unid_hospitalar    NUMBER NOT NULL,
    cd_unid_hospitalar    NUMBER,
    nm_uinid_hospitalar   VARCHAR2(50),
    nm_origem_dados       VARCHAR2(40)
);

ALTER TABLE dim_unid_hospitalar ADD CONSTRAINT dim_unid_hospitalar_pk PRIMARY KEY ( sk_unid_hospitalar );

CREATE TABLE fto_venda (
    sk_unid_hospitalar   NUMBER NOT NULL,
    sk_tempo             NUMBER NOT NULL,
    sk_prod_serv         NUMBER NOT NULL,
    vl_unitario          NUMBER(10, 2) NOT NULL,
    nr_qtde              NUMBER(10, 4),
    vl_total             NUMBER(10, 2),
    vl_icms              NUMBER(10, 2)
);

ALTER TABLE fto_venda
    ADD CONSTRAINT fto_venda_pk PRIMARY KEY ( sk_unid_hospitalar,
                                              sk_tempo,
                                              sk_prod_serv );

ALTER TABLE fto_venda
    ADD CONSTRAINT fk_dim_prod_serv FOREIGN KEY ( sk_prod_serv )
        REFERENCES dim_prod_serv ( sk_prod_serv );

ALTER TABLE fto_venda
    ADD CONSTRAINT fk_dim_tempo FOREIGN KEY ( sk_tempo )
        REFERENCES dim_tempo ( sk_tempo );

ALTER TABLE fto_venda
    ADD CONSTRAINT fk_dim_unid_hospitalar FOREIGN KEY ( sk_unid_hospitalar )
        REFERENCES dim_unid_hospitalar ( sk_unid_hospitalar );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
